---
- name: Force gather facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['all'] }}"
  when: hostvars[item]['ansible_hostname'] is not defined
  tags:
    - dhcpd_inst
    - dhcpd_conf

- name: Install DHCP server
  yum:
    name: dhcp
    state: present
  notify:
    - start dhcpd
    - enable dhcpd
  tags: dhcpd_inst

- name: Configure DHCP server
  template:
    src: 'dhcpd_conf.j2'
    dest: /etc/dhcp/dhcpd.conf 
  notify: restart dhcpd
  tags: dhcpd_conf
