---
- name: Start vsftpd
  service:
    name: vsftpd
    state: started

- name: Enable vsftpd
  service: 
    name: vsftpd
    enabled: yes

- name: Restart vsftpd
  service:
    name: vsftpd
    state: restarted
