---
# To Do:
# Use Valut to configure vsftpd to use password and local user instead of anonymous login.
- name: Import vsftpd installation tasks
  import_tasks: vsftpd_install.yml

- name: Import vsftpd configuration tasks
  import_tasks: vsftpd_config.yml

- name: Import vsftpd OS configuration tasks
  import_tasks: vsftpd_os.yml
