---
- name: Create a directory if it does not exist
  file:
    path: "{{ ftp_directory }}"
    state: directory
    mode: '0755'
  tags: vsftpd_conf

- name: Configure FTP server
  template:
    src: 'vsftpd_conf.j2'
    dest: /etc/vsftpd/vsftpd.conf
  notify: Restart vsftpd
  tags: vsftpd_conf
