---
- name: Start dhcpd service
  service:
    name: dhcpd
    state: started
- name: Enable dhcpd service
  service: 
    name: dhcpd
    enabled: yes
- name: Restart dhcpd service
  service:
    name: dhcpd
    state: restarted
