---
- name: Import named installation tasks
  import_tasks: named_install.yml

- name: Import named configuration tasks
  import_tasks: named_config.yml

- name: Import named OS configuration tasks
  import_tasks: named_os.yml
