---
- name: Force gather facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hostvars[item]['ansible_hostname'] is not defined
  loop: "{{ groups['all'] }}"
  tags: named_conf

- name: Configure DNS server
  template:
    src: 'named_conf.j2'
    dest: /etc/named.conf
  notify: Restart named
  tags: named_conf

- name: Configure DNS zone
  template:
    src: 'zone_file.j2'
    dest: /var/named/db.{{ ns_zone }}
  notify: Restart named
  tags: named_conf
